### ISSUE TITLE
API - GET products

### ISSUE THREAD

**Issue by ghost** [trebaxa/kuwago_api_client#1]
wenn ich die Methode _**get products**_ aufrufe, bekomme ich dann den aktuellen Bestand mitgesendet?

Oder anders: Bekomme ich mit _**get products**_ alle Artikel, mit allen Attributen?

**Comment by trebaxa** [comment]
Mit get_products kommt der Gesamtbestand mit. Das Feld heisst: lager_count
Mit get_stock kommt der gesamte Lager Verlauf von allen Produkte rein. Übergibt man stock_pid, so kommt nur der Stockverlauf von einem bestimmten Artikel. Beispiel:
$arr = kuwago_client::call('get_stock', array('stock_pid' => '11111111') );

Mit get_stock_locations können alle Standorte abgerufen werden. Die readme wurde entsprechend ergänzt.
