### ISSUE TITLE
API GET Kreditoren

### ISSUE THREAD

**Issue by ghost** [trebaxa/kuwago_api_client#3]
Eine GET Methode, mit der ich die Kreditoren auslesen kann:

| Attribut |
| --- |
| id |
| Kreditor |
| Rechnungsbetrag (br) |
| Rechnungsdatum |
| Kostenstelle |
| Text Area |

**Comment by trebaxa** [comment]
Mit get_vendors können alle Kreditoren abgerufen werden. Was du meinst sind wohl eher die Buchungen wie Ausgaben und/oder Einnahmen zu Debitoren. Ausgaben können mit get_costs abgerufen werden.
