### ISSUE TITLE
Lagerbestand > noch nicht gelieferte Artikel > Lieferzeit fehlt

### ISSUE THREAD

**Issue by ghost** [trebaxa/kuwago_api_client#5]
## Request

```
// Stock amount history of all articles
$stock_all = kuwago_client::call('get_stock', array() );
```

## Expected Result

Bucht man einen Lager-Zugang in der Zukunft, wird das Lieferdatum ausgegeben.

## Effective Result

Das Lieferdatum enthält keinen Wert:
```
stock_deliverydate: "0000-00-00"
```

### Frontend
<img width="1135" alt="Screen Shot 2021-03-10 at 04 11 09" src="https://user-images.githubusercontent.com/2051670/110532227-8648fc00-8157-11eb-9a9f-4ccadf478ab8.png">

### Request Preview
<img width="1033" alt="Screen Shot 2021-03-10 at 04 18 19" src="https://user-images.githubusercontent.com/2051670/110532540-eb9ced00-8157-11eb-8191-59705b214066.png">

**Comment by trebaxa** [comment]
Behoben. stock_deliverydate bitte neu erfassen.

**Comment by ghost** [comment]
Danke !! Super schnell .
