### ISSUE TITLE
Frontend -> Angebot anlegen -> Diverses

### ISSUE THREAD

**Issue by ghost** [trebaxa/kuwago_api_client#6]
### Steps

1. Kunde ausgewählt
2. Angebot gedrückt
3. Im Overlay den Titel eingegeben und _**'Weiter'**_ gedrückt 

### Expected Result

Das Overlay schliesst sich und man kann mit der Bearbeitung weitermachen.

### Actual Result
Das Overlay schliesst sich nicht, man muss durch drücken von _**'Close'**_ das Overlay manuell schliessen. Drückt man 2 X auf _**'Weiter'**_ , dann werden 2 Angebote erstellt.

<img width="1033" alt="Screen Shot 2021-03-10 at 04 27 00" src="https://user-images.githubusercontent.com/2051670/110533955-7e8a5700-8159-11eb-9a6a-32e014e8ae23.png">

<img width="389" alt="Screen Shot 2021-03-10 at 04 35 57" src="https://user-images.githubusercontent.com/2051670/110534538-2738b680-815a-11eb-9da0-2221c8ce0e66.png">

**Comment by trebaxa** [comment]
Leider nicht reproduzierbar. Bitte einmal STRG+F5 drücken und noch einmal probieren.

**Comment by ghost** [comment]
Danke, funktioniert wie erwartet.
